-- MySQL Script generated by MySQL Workbench
-- Tue Jun 23 09:14:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`department` (
  `departmentname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`departmentname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `employee_ firstname` VARCHAR(45) NOT NULL,
  `employee_lastname` VARCHAR(45) NOT NULL,
  `employee_basesalary` FLOAT NOT NULL,
  `employee_experience(months)` INT NOT NULL,
  `department_departmentname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_Employee_Department1_idx` (`department_departmentname` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`department_departmentname`)
    REFERENCES `project`.`department` (`departmentname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`retirement plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`retirement plan` (
  `retirementplan_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `retirementplan_percentage` FLOAT NOT NULL,
  `retirementplan_deduction` FLOAT NOT NULL,
  PRIMARY KEY (`retirementplan_id`, `employee_id`),
  INDEX `fk_401(k)_Employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_401(k)_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`raise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`raise` (
  `raise_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `raise_percentage` FLOAT NOT NULL,
  `raise_increment` FLOAT NOT NULL,
  PRIMARY KEY (`raise_id`, `employee_id`),
  INDEX `fk_Raise_Employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Raise_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `address_street` VARCHAR(45) NOT NULL,
  `address_city` VARCHAR(45) NOT NULL,
  `address_state` VARCHAR(45) NOT NULL,
  `address_zipcode` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`address_id`, `employee_id`),
  INDEX `fk_address_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`bonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`bonus` (
  `bonus_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `bonus_percentage` FLOAT NOT NULL,
  `bonnus_increment` FLOAT NOT NULL,
  PRIMARY KEY (`bonus_id`, `employee_id`),
  INDEX `fk_Bonus_Employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bonus_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`taxes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`taxes` (
  `taxes_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `taxes_federal_deduction` FLOAT NOT NULL,
  `taxes_state_deduction` FLOAT NOT NULL,
  `taxes_local_deduction` FLOAT NOT NULL,
  PRIMARY KEY (`taxes_id`, `employee_id`),
  INDEX `fk_Taxes_Employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Taxes_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`health insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`health insurance` (
  `healthinsurance_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `healthinsurance_deduction` FLOAT NOT NULL,
  PRIMARY KEY (`healthinsurance_id`, `employee_id`),
  CONSTRAINT `fk_Health Insurance_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`pension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`pension` (
  `pension_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `pension_percentage` FLOAT NOT NULL,
  `pension_deduction` FLOAT NOT NULL,
  PRIMARY KEY (`pension_id`, `employee_id`),
  CONSTRAINT `fk_Pension_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`penalty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`penalty` (
  `penalty_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `penalty_daysover` INT NOT NULL,
  `penalty_deduction` FLOAT NOT NULL,
  PRIMARY KEY (`penalty_id`, `employee_id`),
  INDEX `fk_Penalty_Employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Penalty_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `project`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
